### ISSUE TITLE
[BUG][Components] Child elements throw error

### ISSUE THREAD

**Issue by griffin8815** [CassandraSpruit/Vivi#14]
**Describe the bug**
```Uncaught TypeError: child.startLoad is not a function```

**To Reproduce**
1. Create component
2. In component, create children
3. See error
Idk if it matters but I also created the factory in the component too

**Expected behavior**
Should load

**Screenshots**
![image](https://user-images.githubusercontent.com/59840321/72291067-34204f80-3614-11ea-8867-a7e5a2825438.png)

**Desktop (please complete the following information, if applicable):**
 - Browser: Chrome

**Comment by griffin8815** [comment]
I also get this error but idk if its the same thing:
```Error adding child node: title-section. No root component has been set yet.```

Pretty sure I set the root thats set in the module factory constructor.

**Comment by CassandraSpruit** [comment]
👋 Hey thanks for adding an issue on here! I really appreciate it. I can take a look and let you know.

As for the second part: Yeah, that's separate. It doesn't seem to be affecting anything, but shouldn't be there in the first place. I'll file it in another issue.

**Comment by CassandraSpruit** [comment]
Fixed in 80004bb77dd90f0730dc0928a5adfb2f0abbb7f1
